// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyCBmDDakLYqbZGL_WZ-iHQ6AkX6PlD6jFw',
    appId: '1:221004408182:web:18cf5b58d60700ce7dc657',
    messagingSenderId: '221004408182',
    projectId: 'flutter-proyects-de055',
    authDomain: 'flutter-proyects-de055.firebaseapp.com',
    storageBucket: 'flutter-proyects-de055.firebasestorage.app',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyBRgoHxyrpDBdQI2T0fnRbYncdwqOWl0WU',
    appId: '1:221004408182:android:0b382f27c7b646d27dc657',
    messagingSenderId: '221004408182',
    projectId: 'flutter-proyects-de055',
    storageBucket: 'flutter-proyects-de055.firebasestorage.app',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyAFyVdyMoUlBdNcwPDj6t4yHo2Nji27OOs',
    appId: '1:221004408182:ios:b1eed2c07f02ab887dc657',
    messagingSenderId: '221004408182',
    projectId: 'flutter-proyects-de055',
    storageBucket: 'flutter-proyects-de055.firebasestorage.app',
    iosBundleId: 'com.example.pushApp',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyAFyVdyMoUlBdNcwPDj6t4yHo2Nji27OOs',
    appId: '1:221004408182:ios:b1eed2c07f02ab887dc657',
    messagingSenderId: '221004408182',
    projectId: 'flutter-proyects-de055',
    storageBucket: 'flutter-proyects-de055.firebasestorage.app',
    iosBundleId: 'com.example.pushApp',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyCBmDDakLYqbZGL_WZ-iHQ6AkX6PlD6jFw',
    appId: '1:221004408182:web:8f7428a29cde32be7dc657',
    messagingSenderId: '221004408182',
    projectId: 'flutter-proyects-de055',
    authDomain: 'flutter-proyects-de055.firebaseapp.com',
    storageBucket: 'flutter-proyects-de055.firebasestorage.app',
  );
}
